#!/usr/bin/env ruby

require 'open-uri'
require 'redis'

redis = Redis.new

cache_price = redis.get 'dolartoday_price'

if cache_price.nil?
  doc = open('http://ehi5mkclj24snjkmsqex.r.worldssl.net/custom/rate.js').read
  current_price = doc.match(/"dolartoday":(.{5})/).captures.first
  redis.set 'dolartoday_price', current_price
  redis.expire 'dolartoday_price', 14400
else
  current_price = cache_price
end

puts current_price
